### ISSUE TITLE
Add MAC addresses to the Common Information Model

### ISSUE THREAD

**Issue by l0x-c0d3z** [Cyb3rWard0g/OSSEM#32]
We're using OSSEM as a standard model for the platform we're building. Currently OSSEM does not define field names for MAC addresses. We would like to add those.

**Comment by Cyb3rWard0g** [comment]
Hey @l0x-c0d3z ! sorry for the late response. Yeah that would be great. would you mind sharing what you have put together for your platform via a PR? I would like to know what works for you and I am sure it would benefit this project. Let me know if you could do that? Thank you in advance!

**Comment by Cyb3rWard0g** [comment]
NVM! 😆 sorry I didnt check the PRs first. I appreciate your help and contribution to the project @l0x-c0d3z ! 👍
