### ISSUE TITLE
Sysmon data dictionary Update

### ISSUE THREAD

**Issue by Cyb3rPanda** [Cyb3rWard0g/OSSEM#35]
- Event id 3: Field name **DestinationHostName** is missing.
![image](https://user-images.githubusercontent.com/33077805/60816378-a39a1b80-a167-11e9-86d6-103a08e5c437.png)

- Event id 15: Field name **Hashes** should be changed to **Hash** based on the event XML.
![image](https://user-images.githubusercontent.com/33077805/60816297-66ce2480-a167-11e9-82bb-28f402bb35b4.png)

- In events 1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 18 the field name **RuleName** is missing. The standard name might be **tag**
![image](https://user-images.githubusercontent.com/33077805/60816500-d93f0480-a167-11e9-8f07-930f5c1d5dd7.png)

**Comment by Cyb3rWard0g** [comment]
Thak you @Cyb3rPanda ! 👍
